apps/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^edit/(?P<id>\d*)$', views.edit, name="edit"),
    url(r'^update/(?P<id>\d*)$', views.update, name="update"),
    url(r'^messages/(?P<id>\d*)$', views.show, name="show"),
    url(r'^addUser$', views.addUser, name="addUser"),
    url(r'^addMessage/(?P<id>\d*)$', views.addMessage, name="addMessage"),
    url(r'^addComment/(?P<id>\d*)$', views.addComment, name="addComment"),
    url(r'^deleteUser/(?P<id>\d*)$', views.deleteUser, name="deleteUser")
]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login$', views.login, name="login"),
    url(r'^register$', views.register, name="register"),
    url(r'^logout$', views.logout, name="logout")
]

userdb/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace="login")),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="db"))
]

apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..login.models import User

class MessageManager(models.Manager):
    def addMessage(self, postData):
        auth = User.objects.get(id=postData['author_id'])
        rec = User.objects.get(id=postData['recipient_id'])
        Message.objects.create(message=postData['message'], recipient=rec, author=auth)

class CommentManager(models.Manager):
    def addComment(self, postData):
        auth = User.objects.get(id=postData['author_id'])
        message = Message.objects.get(id=postData['message_id'])
        return Comment.objects.create(comment=postData['comment'], message=message, author=auth)

class Message(models.Model):
    message = models.TextField()
    recipient = models.ForeignKey(User, related_name="messages_for")
    author = models.ForeignKey(User, related_name="messages_by")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = MessageManager()

class Comment(models.Model):
    comment = models.TextField()
    message = models.ForeignKey(Message, related_name="comments")
    author = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CommentManager()

apps/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User, Message, Comment

def index(request):
    context = { 'users': User.objects.all() }
    return render(request, 'dashboard/index.html', context)

def addUser(request):
    if request.session['user_level'] == 9:
        if request.method == "GET":
            return render(request, 'dashboard/addUser.html')
        elif request.method == "POST":
            response_from_models = User.objects.addUser(request.POST)
            if response_from_models['status']:
                return redirect('db:index')
            else:
                for error in response_from_models['info']:
                    messages.add_message(request, messages.ERROR, error)
                return redirect('db:addUser')
    else:
        return render(request, 'dashboard/deny.html')

def edit(request, id):
    if request.session['user_level'] != 9 and request.session['user_id'] != int(id):
        return render(request, 'dashboard/deny.html')
    else:
        context = { 'user': User.objects.get(id=id) }
        return render(request, 'dashboard/profile.html', context)

def update(request, id):
    if request.method == "POST":
        postData = {'id': id}
        if request.POST['type'] == "info":
            postData['first_name'] = request.POST['first_name']
            postData['last_name'] = request.POST['last_name']
            postData['email'] = request.POST['email']
            try:
                postData['level'] = request.POST['level']
            except:
                pass
            fromModels = User.objects.updateInfo(postData)
            if fromModels['status']:
                messages.add_message(request, messages.INFO, "Changes saved.", extra_tags="personalinfo")
            else:
                for error in fromModels['info']:
                    messages.add_message(request, messages.ERROR, error, extra_tags="personalinfo")
        elif request.POST['type'] == "password":
            postData['password'] = request.POST['password']
            postData['confirm'] = request.POST['confirm']
            fromModels = User.objects.updatePassword(postData)
            if fromModels['status']:
                messages.add_message(request, messages.INFO, "Password updated.", extra_tags="password")
            else:
                for error in fromModels['info']:
                    messages.add_message(request, messages.ERROR, error, extra_tags="password")
        elif request.POST['type'] == "description":
            postData['description'] = request.POST['description']
            fromModels = User.objects.updateDescription(postData)
            if fromModels['status']:
                messages.add_message(request, messages.INFO, "Description updated.", extra_tags="desc")
            else:
                for error in fromModels['info']:
                    messages.add_message(request, messages.ERROR, error, extra_tags="desc")
        return redirect('db:edit', id=id)
    else:
        return redirect('db:index')

def show(request, id):
    context = { 'user': User.objects.get(id=id) }
    return render(request, 'dashboard/messages.html', context)

def addMessage(request, id):
    postData = { 'author_id': request.session['user_id'],
                 'recipient_id': id,
                 'message': request.POST['message'] }
    Message.objects.addMessage(postData)
    return redirect('db:show', id=id)

def addComment(request, id):
    postData = { 'author_id': request.session['user_id'],
                 'message_id': id,
                 'comment': request.POST['comment'] }
    comment = Comment.objects.addComment(postData)
    return redirect('db:show', id=comment.message.recipient.id)

def deleteUser(request, id):
    if request.session['user_level'] == 9:
        User.objects.get(id=id).delete()
        return redirect('db:index')
    else:
        return render(request, 'dashboard/deny.html')

apps/dashboard/templates/dashboard/addUser.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}Add User{% endblock %}
{% block main %}
  <h3>Add a New User</h3>
  {% if messages %}
    <div class="errors">
    {% for message in messages %}
      <p>{{message}}</p>
    {% endfor %}
    </div>
  {% endif %}
  <form class="" action="{% url 'db:addUser' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label>Email: <input type="email" name="email" class="form-control"></label>
    </div>
    <div class="form-group">
      <label>First Name: <input type="text" name="first_name" class="form-control"></label>
    </div>
    <div class="form-group">
      <label>Last Name: <input type="text" name="last_name" class="form-control"></label>
    </div>
    <div class="form-group">
      <label>Password: <input type="password" name="password" class="form-control"></label>
    </div>
    <div class="form-group">
      <label>Confirm Password: <input type="password" name="confirm" class="form-control"></label>
    </div>
    <input type="submit" class="btn btn-primary" value="Create">&nbsp;&nbsp;
    <a href="{% url 'db:index' %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}

apps/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block pagetitle %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'dashboard/css/base.css' %}">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'dashboard/js/base.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Test App</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'db:index' %}">Dashboard</a></li>
            <li><a href="{% url 'db:edit' id=request.session.user_id %}">Profile</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">Welcome, {{request.session.username}}</a></li>
            <li><a href="{% url 'login:logout' %}">Log off</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="main_content">
      {% block main %}
      {% endblock %}
    </div>
    <div class="left">
      {% block main1 %}
      {% endblock %}
    </div>
    <div class="right">
      {% block main2 %}
      {% endblock %}
    </div>
    <div class="main_content">
      {% block mainbottom %}
      {% endblock %}
    </div>
  </body>
</html>

apps/dashboard/templates/dashboard/deny.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}No Access{% endblock %}
{% block main %}
<h3>You do not have access to view this page</h3>
{% endblock %}

apps/dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}User Dashboard{% endblock %}
  {% block main %}
    <h3>Manage Users</h3>
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Created At</th>
        <th>User Level</th>
        {% if request.session.user_level == 9 %}
          <th>Actions</th>
        {% endif %}
      </tr>
      {% for user in users %}
        <tr>
          <td>{{user.id}}</td>
          <td><a href="{% url 'db:show' id=user.id %}">{{user.name}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at|date:'M d, Y'}}</td>
          <td>{{user.user_level}}</td>
          {% if request.session.user_level == 9 %}
          <td><a href="{% url 'db:edit' id=user.id %}">edit</a>&nbsp;&nbsp;&nbsp;
              <a href="{% url 'db:deleteUser' id=user.id %}" class="confirm-delete" data-object-name="{{user.name}}" data-object-id="{{user.id}}">remove</a></td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
    {% if request.session.user_level == 9 %}
    <a href="{% url 'db:addUser' %}" class="btn btn-primary">Add New</a>
    {% endif %}
  {% endblock %}

apps/dashboard/templates/dashboard/messages.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}User Information{% endblock %}
{% block main1 %}
  <h2>{{user.name}}</h2>
  <h5>Registered Since: {{user.created_at|date:'M d, Y'}}</h5>
  <h5>User ID: {{user.id}}</h5>
  <h5>Email Address: {{user.email}}</h5>
  <h5>Description: {{user.description}}</h5>
{% endblock %}
{% block main2 %}
  <h4>Leave a message for {{user.first_name}}</h4>
  <form class="" action="{% url 'db:addMessage' id=user.id %}" method="post">
    {% csrf_token %}
    <textarea name="message" rows="4"></textarea>
    <br>
    <input type="submit" class="btn btn-primary pull-right" value="Post">
  </form>
{% endblock %}
{% block mainbottom %}
<hr>
<div class="userMessages">
  {% for message in user.messages_for.all %}
  <p><b><a href="{% url 'db:show' id=message.author.id %}">{{message.author.name}}</a> wrote </b> <i>({{message.created_at|timesince}} ago)</i>:</p>
  <p></p>
  <p>{{message.message}}</p>
  <div class="comments">
    {% for comment in message.comments.all %}
    <p><b><a href="{% url 'db:show' id=comment.author.id %}">{{comment.author.name}}</a> wrote </b> <i>({{comment.created_at|timesince}} ago)</i>:</p>
    <p>{{comment.comment}}</p>
    {% endfor %}
    <form class="" action="{% url 'db:addComment' id=message.id %}" method="post">
      {% csrf_token %}
      <textarea name="comment" rows="2"></textarea>
      <br>
      <input type="submit" class="btn btn-primary pull-right" value="Reply">
    </form>
    <br>
  </div>
  {% endfor %}
</div>
{% endblock %}

apps/dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}Edit Profile{% endblock %}
{% block main %}
<h3>Edit Profile</h3>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-lg-3">
      <fieldset>
        <legend>Edit Information</legend>
        {% if messages %}
        <div class="errors">
          {% for message in messages %}
          {% ifequal message.tags "personalinfo error"%}
            <p>{{message}}</p>
          {% endifequal %}
          {% endfor %}
          </div>
        <div class="messages">
          {% for message in messages %}
          {% ifequal message.tags "personalinfo info"%}
            <p>{{message}}</p>
          {% endifequal %}
          {% endfor %}
          </div>
        {% endif %}
        <form class="" action="{% url 'db:update' id=user.id %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label>Email Address: <input type="email" name="email" class="form-control" value="{{user.email}}"></label>
          </div>
          <div class="form-group">
            <label>First Name: <input type="text" name="first_name" class="form-control" value="{{user.first_name}}"></label>
          </div>
          <div class="form-group">
            <label>Last Name: <input type="text" name="last_name" class="form-control" value="{{user.last_name}}"></label>
          </div>
          {% if request.session.user_level == 9 %}
          <div class="form-group">
            <label>Level: <select class="form-control" name="level">
              <option value="9" {% if user.level == 9 %}selected="selected"{% endif %}>Admin</option>
              <option value="1" {% if user.level == 1 %}selected="selected"{% endif %}>Normal</option>
            </select></label>
          </div>
          {% endif %}
          <input type="submit" value="Save" class="btn btn-primary">
          <input type="hidden" name="type" value="info">
        </form>
      </fieldset>
    </div>
    <div class="col col-lg-3">
      <fieldset>
        <legend>Change Password</legend>
        {% if messages %}
        <div class="errors">
          {% for message in messages %}
          {% ifequal message.tags "password error"%}
            <p>{{message}}</p>
          {% endifequal %}
          {% endfor %}
          </div>
        <div class="messages">
          {% for message in messages %}
          {% ifequal message.tags "password info"%}
            <p>{{message}}</p>
          {% endifequal %}
          {% endfor %}
          </div>
        {% endif %}
        <form class="" action="{% url 'db:update' id=user.id %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label>Password: <input type="password" name="password" class="form-control"></label>
          </div>
          <div class="form-group">
            <label>Confirm Password: <input type="password" name="confirm" class="form-control"></label>
          </div>
          <input type="submit" value="Update Password" class="btn btn-primary">
          <input type="hidden" name="type" value="password">
        </form>
      </fieldset>
    </div>
    <div class="col col-lg-6">
      <fieldset>
        <legend>Edit Description</legend>
        {% if messages %}
        <div class="errors">
          {% for message in messages %}
          {% ifequal message.tags "desc error"%}
            <p>{{message}}</p>
          {% endifequal %}
          {% endfor %}
          </div>
        <div class="messages">
          {% for message in messages %}
          {% ifequal message.tags "desc info"%}
            <p>{{message}}</p>
          {% endifequal %}
          {% endfor %}
          </div>
        {% endif %}
        <form class="" action="{% url 'db:update' id=user.id %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <textarea name="description" rows="4" cols="70" value="">{{user.description}}</textarea>
            <br><br>
            <input type="submit" value="Save" class="btn btn-primary">
            <input type="hidden" name="type" value="description">
          </div>
        </form>
      </fieldset>
    </div>
  </div>
</div>
{% endblock %}